/**
 * Typed errors thrown by lib/bookings/* functions.
 * Route handlers catch BookingError and map the .code to an HTTP status
 * via the ERROR_HTTP_STATUS map below. Untyped errors → 500.
 */

export const ERROR_CODES = Object.freeze({
    MISSING_FIELDS: 'MISSING_FIELDS',
    INVALID_ACTION: 'INVALID_ACTION',
    UNAUTHORIZED: 'UNAUTHORIZED',
    LIMIT_REACHED: 'LIMIT_REACHED',
    BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
    BOOKING_ALREADY_DECIDED: 'BOOKING_ALREADY_DECIDED',
    BOOKING_CONFLICT: 'BOOKING_CONFLICT',
    LOCK_CONFLICT: 'LOCK_CONFLICT',
    LOCK_NOT_FOUND: 'LOCK_NOT_FOUND',
    LOCK_EXPIRED: 'LOCK_EXPIRED',
    CONCURRENT_LOCK: 'CONCURRENT_LOCK',
    CONCURRENT_BOOKING: 'CONCURRENT_BOOKING',
    DOUBLE_BOOKING_PREVENTED: 'DOUBLE_BOOKING_PREVENTED',
    STAFF_NOT_FOUND: 'STAFF_NOT_FOUND',
    STAFF_FORBIDDEN: 'STAFF_FORBIDDEN',
});

export const ERROR_HTTP_STATUS = Object.freeze({
    [ERROR_CODES.MISSING_FIELDS]: 400,
    [ERROR_CODES.INVALID_ACTION]: 400,
    [ERROR_CODES.BOOKING_ALREADY_DECIDED]: 400,
    [ERROR_CODES.UNAUTHORIZED]: 401,
    [ERROR_CODES.LIMIT_REACHED]: 403,
    [ERROR_CODES.STAFF_FORBIDDEN]: 403,
    [ERROR_CODES.LOCK_NOT_FOUND]: 404,
    [ERROR_CODES.BOOKING_NOT_FOUND]: 404,
    [ERROR_CODES.STAFF_NOT_FOUND]: 404,
    [ERROR_CODES.BOOKING_CONFLICT]: 409,
    [ERROR_CODES.LOCK_CONFLICT]: 409,
    [ERROR_CODES.CONCURRENT_LOCK]: 409,
    [ERROR_CODES.CONCURRENT_BOOKING]: 409,
    [ERROR_CODES.DOUBLE_BOOKING_PREVENTED]: 409,
    [ERROR_CODES.LOCK_EXPIRED]: 410,
});

export class BookingError extends Error {
    constructor(code, message, details = {}) {
        super(message);
        this.name = 'BookingError';
        this.code = code;
        this.details = details;
    }
}
